<?php

/*
 * Implements hook_menu
 */

function custom_modules_menu()
{
    $items = array();
    $items['contacts/form'] = array(
        'title' => t('Форма обратной связи'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('first_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}

function first_form()
{
    $form = array();
    $form['name'] = array(
        '#title' => t('Ваше имя'),
        '#type' => 'textfield',
        '#required' => TRUE,
        '#description' => t('Пожалуйста, введите Ваше имя'),
    );
    $form['email'] = array(
        '#title' => t('Электронная почта'),
        '#type' => 'textfield',
        '#description' => t('Пожалуйста, ведите Вашу почту'),
    );
    $form['text'] = array(
        '#title' => t('Ваше сообщение'),
        '#type' => 'textarea',
        '#description' => t('Пожалуйста, введите Ваш текст'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('send'),
    );

    return $form;

}