<?php

//drupal_add_js('js/libs/jquery.js');
//drupal_add_js('js/libs/underscore.js');
//drupal_add_js('js/chartist/dist/chartist.min.js');
//drupal_add_js('js/libs/moment.js');
//drupal_add_js('js/jquery.ui/jquery-ui.min.js');
//drupal_add_js('js/myweather.js');

//drupal_add_css('js/chartist/dist/chartist.min.css');
//drupal_add_css('js/jquery-ui/jquery-ui.css');
//drupal_add_css('css/style.css');


/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function myweather_block_info(){
    $block['my_widget'] = array(
        'info' => t('My Widget Weather'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $block;
}

/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function myweather_block_view($block_key){
    $block = array();
    if($block_key == 'my_widget'){
        $block['subject'] = t('Custom Widget Weather');
        $block['content'] = myweather_render_widget();
    }
    return $block;
}

function myweather_render_widget(){
   // return 'my test function';
    $html =<<<HTML
<div id="target">
    <div class="section-widget-one">
        <div class="title-chisinau"><h3>Temperature in Chisinau:</h3></div>
        <div class="current-city"></div>
    </div>
    <div class="section-widget-two">
        <div class="title-current-city"><h3>Temperature in your city:</h3></div>
        <div class="location-city"></div>
    </div>
</div>

<script type="text/template" id="template">
    <div class="container-widget-chisinau">
        <div class="layout-widget">
            <div class="container-top">
                <div class="section-left">
                    <div class="city-name"><%= city %></div>
                </div>
                <div class="section-center">
                    <div class="icon-weather">
                        <img src=<%= iconUrl %>
                        alt=""/>
                    </div>
                </div>
                <div class="section-right">
                    <div class="temperature"><%= temp %>&#176;С</div>
                </div>
            </div>
            <div class="container-bottom">
                <div class="data-source">
                    <a href="/statistic.php">weather last 7 days</a>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="template-location">
    <div class="container-widget-location">
        <div class="layout-widget-location">
            <div class="container-top-location">
                <div class="section-left-location">
                    <div class="city-name-location"><%= cityLoc %>, <%= countryLoc %></div>
                </div>
                <div class="section-center-location">
                    <div class="icon-weather-location">
                        <img src=<%= iconUrlLoc %>
                        alt=""/>
                    </div>
                </div>
                <div class="section-right-location">
                    <div class="temperature-location"><%= tempLoc %>&#176;С</div>
                </div>
            </div>
        </div>
    </div>
</script>
<!--<script type="text/javascript">-->
    <!--$(document).ready(function () {-->
        <!--renderWidget();-->
    <!--});-->
<!--</script>-->
HTML;

    return $html;
}



/**
 * Implements hook_menu().
 */
function myweather_menu() {

    $items['statistics'] = array(
        'title' => 'Statistics for widget weather',
        'page callback' => 'get_statistics_for_chisinau',
        'access callback' => TRUE,
        'file' => 'statistics.pages.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );

    return $items;
}

